### ISSUE TITLE
Downloading homework is impossible over slow internet connections

### ISSUE THREAD

**Issue by lwahonen** [rage/tmc-vscode#600]
Opening the workspace times out with "Runtime Error — Process didn't seem to finish or was taking a really long time. — Runtime Error: Process didn't seem to finish or was taking a really long time.".

The download progress tends to get to around halfway through the exercises before it times out. There is no resume, so it keeps downloading the first couple of dozen over and over again.

There should either be a resume, or a more sophisticated time out that keeps an eye on the download progress, instead of just timing out if all 152(!) files don't download fast enough.

<img width="589" alt="Screen Shot 2021-04-04 at 10 49 45 PM" src="https://user-images.githubusercontent.com/3996667/113519969-82fb3180-9598-11eb-96f1-6e5964184ca9.png">
<img width="1017" alt="Screen Shot 2021-04-04 at 10 55 01 PM" src="https://user-images.githubusercontent.com/3996667/113520014-cfdf0800-9598-11eb-8266-2dc8ec65f3bc.png">

**Comment by jolampi** [comment]
We apologize that you are having issues with the extension. It doesn't seem right that exercises need to be re-downloaded even if some of the downloads fail. In this case the issue is related to a process timeout, but simply increasing that treshold wouldn't fix the underlying problem. We will investigate for a proper solution.
